### ISSUE TITLE
Facing issues with integration.

### ISSUE THREAD

**Issue by qburst-akhiln** [PTNUSASATUINTIARTHA-DOKU/jokul-java-library#1]
Is this the right library to test when I want to integrate Payment gateway for Credit Card Payments with doku? The customer service seems slow.

**Comment by ariefrizkyr** [comment]
> Is this the right library to test when I want to integrate Payment gateway for Credit Card Payments with doku? The customer service seems slow.

Hi! This is the library for our new Payment Gateway system named Jokul. 

If you wish to integrate with Jokul (our new Payment Gateway), you can register and get the credential from https://sandbox.doku.com/bo/login. Once you are ready to integrate with your Production environment, you can create and register your business to https://jokul.doku.com/bo/login

Thank you.
